version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_BASICAUTH_ENCRYPT: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb


  # fastify-backend:
  #   image: node:18
  #   container_name: fastify-backend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/second-brain
  #   depends_on:
  #     - mongodb

  # angular-frontend:
  #   image: node:18
  #   container_name: angular-frontend
  #   restart: always
  #   ports:
  #     - 4200:4200
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - fastify-backend

volumes:
  mongodb_data:
