version: "3"
services:
  angular-app:
    image: node:18.16.1
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
    working_dir: /app
    command: npm start
    depends_on:
      - node-server
  node-server:
    image: node:18.16.1
    ports:
      - "3000:3000"
    volumes:
      - ./node-server:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
